
services:

  api:
    build:
      context: ./images/api
    container_name: "api"
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      TOKEN_ENCRYPTION: ${TOKEN_ENCRYPTION}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    volumes:
      - ./images/api/src:/usr/app/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./images/frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./images/frontend/src:/app/src
      - ./images/frontend/public:/app/public
      - ./images/frontend/index.html:/app/index.html
      - ./images/frontend/vite.config.ts:/app/vite.config.ts
      - ./images/frontend/tsconfig.json:/app/tsconfig.json
      - ./images/frontend/tsconfig.app.json:/app/tsconfig.app.json
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - backend
    restart: unless-stopped


  db:
    image: "postgres:18"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./_volumes/pg:/var/lib/postgresql/
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DATABASE} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5


networks:
  backend:
    driver: bridge
